taxi_co2:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '/Users/clairebassett/Library/CloudStorage/OneDrive-Personal/Documents/University of Virginia/Classes/Fall 25/DS 3022/ds3022-data-project-1/emissions.duckdb'
      schema: main